# This is a basic workflow to help you get started with Actions

name: CI

defaults:
  run:
    shell: bash -ieo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, alpha ]
  pull_request:
    branches: [ master, alpha ]
  schedule:
    - cron: '0 0 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-nova:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install boost
        run: |
          ./install_boost.sh

      - name: install google stuffs 
        run: |
          ./install_glog.sh
          ./install_gtest.sh
          ./install_gperftools.sh
          ./install_tcmalloc.sh

      - name: install zmq
        run: |
          ./install_zmq.sh

      - name: install parallel-hashmap
        run: |
          ./install_phmap.sh

      - name: install zaf
        run: |
          ./install_zaf.sh

      - name: install coll
        run: |
          ./install_coll.sh

      - name: install nova
        run: |
          ./install_nova.sh

      - name: install rdkafka
        run: |
          ./install_rdkafka.sh

      - name: install cppredis
        run: |
          ./install_cppredis.sh

      - name: install voltdb-client-cpp
        run: |
          ./install_voltdb.sh

  build-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install cmake
        run: |
          ./install_cmake.sh
